### ISSUE TITLE
Add Message

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-cobralily#13]
## User Story
As a user, I should be able to add messages by clicking enter.

## AC
**Given** A user navigates to your page
**Then** they type in the input field
**And** when they hit enter a new message should be created
**And** the message should show up in the new chat window

## Dev Notes
* There should be a submit button with the `id="submit-message-button"` with an event listener attached to it.
* this eventlistener should be a jquery `$("#target").keydown()` targeted to the enter key (see comments)
* this eventlistener should call a function called `addMessage` which uses `.val()` to get the entry the user has input and then uses the `.push()` array method to push the new message into the array of `messages`
* the DOM should then be reprinted to display the new message along with those already existing

**Comment by delindell** [comment]
https://api.jquery.com/val/

**Comment by delindell** [comment]
https://api.jquery.com/keydown/

**Comment by delindell** [comment]
key mapping website:

http://keycode.info/
