### ISSUE TITLE
Large Text

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-cobralily#15]
## User Story
As a user, with tired eyes, I should be able to chat with large text.

## AC
**Given** A user navigates to your page
**Then** they should see a checkbox below the input field called "Large Text"
**And** they should be able to click this checkbox
**And** when the checkbox is selected all the message text should be larger

## Dev Notes
* create buttons.js file in components 
* create button with `id="largeText"`
* use jquery .click to target id
* call function `makeTextLarge`
* refer to w3schools link below

**Comment by bethh56** [comment]
https://stackoverflow.com/questions/33336130/how-can-i-make-a-button-that-imports-a-css-file

**Comment by bethh56** [comment]
https://www.w3schools.com/jquery/html_attr.asp

**Comment by bethh56** [comment]
https://www.w3schools.com/jquery/jquery_css.asp

**Comment by Nikababy01** [comment]
pr looks good 👍
