### ISSUE TITLE
Delete Message

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-cobralily#16]
## User Story
As a user I should be able to delete messages my messages.

## AC
**Given** A message on your page
**Then** there should be a delete button for each message (that belongs to your user)
**And** when the button is pushed the message should no longer exist

## Dev Notes
* Each message should have a delete button attached to it with the unique message `id=${messages.id}`. Each button should have a jquery selector and eventlistener attached to it.
* The eventlistener should called a function called `deleteMessage` that uses the `splice` array method to remove the specific message from the array. Then it should reprint the DOM.

**Comment by delindell** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice

**Comment by delindell** [comment]
Also refer to the sorting hat expel button homework

**Comment by Nikababy01** [comment]
👍
