### ISSUE TITLE
Display Message

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-cobralily#17]
## User Story
As a user, when the page loads, I should see messages.

## AC
**Given** A user navigates to your page
**Then** they should see the 5 messages from `helpers/data/messageData.js`
**And** when they add messages it should add them to the list

## Dev Notes
* create `message.js` file in components
* make div in html with `id="messageContainer"`
* create a function called `messageBuilder` that will print all messages to dom using `printToDom`
* use bootstrap card to display messages

**Comment by bethh56** [comment]
https://getbootstrap.com/docs/4.4/components/card/#list-groups
