### ISSUE TITLE
Message Users

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-cobralily#18]
## User Story
As a user, I want to easily be able to tell who sent each message.

## AC
**WHEN** the page loads
**THEN** i should see messages
**AND** each message should show who wrote that message

## Dev notes
* The `messages` array should have a `userId` object
* In the user array the users should have userId that corresponds to the userId in the messages array
* use the find array method to compare the IDs 
* something like this: 
```const createMessageList =(messages) => {
const users= usersData.getUsers();
let domString=
messages.forEach((message)=>{
const messageUsers= users.find((x) = > x.id === message.userId);
domString += messageCard.createMessageCard(message, messageUser);
}

**Comment by bethh56** [comment]
refer to bearwatcher and hogwarts

**Comment by bethh56** [comment]
https://api.jquery.com/val/
